version: 2
updates:
  # ---------------------------------
  # --- Usage sur la branche MAIN ---
  # ---------------------------------
  # Ensure GitHub Actions are used in their latest version
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"

  # Strategy for composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 100
    versioning-strategy: "increase"
    groups:
      dev-dependencies:
        dependency-type: "development"
    target-branch: "main"

  # Strategy for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "development"
    open-pull-requests-limit: 100
    versioning-strategy: "increase"
    groups:
      dev-dependencies:
        dependency-type: "development"
    target-branch: "main"

  # ------------------------------------------
  # --- Usage sur la branche 10.0/bugfixes ---
  # ------------------------------------------
  # Ensure GitHub Actions are used in their latest version
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "10.0/bugfixes"

  # Strategy for composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 100
    versioning-strategy: "increase"
    groups:
      dev-dependencies:
        dependency-type: "development"
    target-branch: "10.0/bugfixes"

  # Strategy for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "development"
